--Exercise 6
--1-6 Tennis query

--NAME, INITIALS and number of sets won for each player
--subselect
SELECT NAME,
       INITIALS,
       WONSETS
FROM PLAYERS,
     (SELECT PLAYERNO, SUM(WON) WONSETS
      FROM MATCHES
      GROUP BY PLAYERNO) SUBQ
WHERE PLAYERS.PLAYERNO = SUBQ.PLAYERNO;

--join
SELECT NAME, INITIALS, SUM(WON)
FROM PLAYERS,
     MATCHES
WHERE PLAYERS.PLAYERNO = MATCHES.PLAYERNO
GROUP BY NAME, INITIALS;

--NAME, PEN_DATE and AMOUNT sorted in descending order by AMOUNT


--join
SELECT NAME, PEN_DATE, AMOUNT
FROM PENALTIES,
     PLAYERS
WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
ORDER BY AMOUNT DESC;


SELECT NAME, SUM(AMOUNT) AS PENALTY
FROM PENALTIES,
     PLAYERS
WHERE PENALTIES.PLAYERNO = PLAYERS.PLAYERNO
GROUP BY PENALTIES.PLAYERNO, NAME
ORDER BY PENALTY DESC;


--TEAMNO, NAME (of the captain) per team
SELECT TEAMNO, NAME AS CAPTAIN
FROM TEAMS,
     PLAYERS
WHERE TEAMS.PLAYERNO = PLAYERS.PLAYERNO;


SELECT PLAYERS.NAME, (SELECT TEAMNO FROM TEAMS WHERE PLAYERS.PLAYERNO=TEAMS.PLAYERNO) AS "Team"
FROM PLAYERS
WHERE PLAYERS.PLAYERNO IN (SELECT PLAYERNO
FROM TEAMS);


--NAME (player name), WON, LOST of all won matches
SELECT NAME, WON, LOST
FROM PLAYERS,
     MATCHES
WHERE PLAYERS.PLAYERNO = MATCHES.PLAYERNO
AND WON>LOST;


--PLAYERNO, NAME and penalty amount for each team player. If a player has not yet received a penalty, it should still be issued. Sorting should be done in ascending order of penalty amount
SELECT PLAYERS.PLAYERNO, NAME, SUM(AMOUNT) AS TOTALPEN
FROM PLAYERS,
     PENALTIES
WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
GROUP BY PLAYERS.PLAYERNO, NAME
ORDER BY TOTALPEN;


--6-9 EmptDept query

--in which city does the employee Allen work?
SELECT LOC AS CITY
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'ALLEN');

--search for all employees who earn more than their supervisor
SELECT *
FROM EMP X
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE JOB = 'MANAGER'
               AND X.DEPTNO = DEPTNO);

--output the number of hires in each year
SELECT COUNT(*) AS NEW_HIRES, EXTRACT(YEAR FROM HIREDATE) AS YR
FROM EMP
GROUP BY EXTRACT(YEAR FROM HIREDATE);

--output all employees who have a job like an employee from CHICAGO.
SELECT *
FROM EMP
WHERE JOB IN (SELECT JOB
              FROM EMP
              WHERE DEPTNO IN (SELECT DEPTNO
                               FROM DEPT
                               WHERE LOC = 'CHICAGO'))